### ISSUE TITLE
Reproducing the pycocoeval metrics?

### ISSUE THREAD

**Issue by jmhessel** [Seleena/Image-Caption-Evalaution#4]
Hi There!

Thanks for the code release, and for the great work! I was wondering if you could possibly make available the code you used to reproduce the correlations in Table 1. I've tried computing them myself, but I'm having some trouble getting matching results compared to TIGEr.

If you're interested in more details, I shared the script I used alongside some other sanity checks I did here:

https://github.com/ck0123/improved-bertscore-for-image-captioning-evaluation/issues/3

I'll spare the full details, but after following the instructions you mentioned in the paper (e.g., lowercase, pycocoeval cap, ptb tokenizer), I get the following correlations for these metrics on composite:

```
Kendall tau bleu: 44.63, spearman 58.98 (Table 1 says: 20.5 / 35.2)
Kendall tau cider: 46.93, spearman 61.51 (Table 1 says: 37.8 / 47.2)
Kendall tau meteor: 47.91, spearman 61.40 (Table 1 says: 37.9 / 46.9)
Kendall tau rouge: 46.06, spearman 59.69 (Table 1 says: 30.7 / 38.3)
Kendall tau spice: 50.40, spearman 63.89 (Table 1 says 41.9 / 51.4)
```
I do recognize my values are different than, e.g., what the original SPICE paper reports. But given that you also reported spearman correlations, it seems like you re-implemented the evaluation from the original SPICE paper and reported similar numbers. I was hoping to walk-through your code to see how my evaluation setup differed. What do you think?

Thanks again!
Jack

**Comment by SeleenaJM** [comment]
Hi Jack,

Thanks for your interest in our work! Please see my answers below. 

1. Kendall Tau
In fact, there are three variants of Kendall tau calculation (please refer to the section of "Accounting for ties" in Wikipedia: 

> https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient). 

We calculated the correlation based on Tau-c. I think this might be the main issue that leads to the different Kendall tau values between yours and ours. For the code of Tau-c calculation, please refer to 

> https://stackoverflow.com/questions/2557863/measures-of-association-in-r-kendalls-tau-b-and-tau-c. Based on this code, we can reproduce the results shown in the SPICE paper. I guess you might use the python package SciPy 

> https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.kendalltau.html to calculate Kendall tau. However, the tau value generated by this package is based on Tau-b. 

2. Spearman
For Spearman, we directly use the R package cor.test 

> (https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor.test) to calculate the correlation and our results have a similar pattern as Kendall tau in both Composite and Flickr8k. 

Hope it is helpful!
Ming

**Comment by jmhessel** [comment]
Hi Ming!

Thank you for the insight regarding the two version of kendall tau! I had tried using `variant='c'` in the newest version of scipy, but it's good to know you were able to reproduce close values to the original spice paper. I've tried both the scipy and R versions of kendalltau (with `variant='c'`) and scipy and R match closely, e.g.,
```
Kendall tau-c bleu-4: 48.095, spearman 58.982, R kendall-c 48.095, R spearman 58.982
```

So, I am still having a bit of trouble, but I can keep looking at it! I'm sure I just have some subtle thing setup wrong.

By the way, would it potentially be possible for you to share the sentence level TIGEr score csv outputs you used for composite and flickr8k? I can recompute them using the instructions you provided alongside this code, but if I avoid introducing another confounding factor (e.g., me computing them improperly) I can perhaps get to the bottom of why my values are so off!

Jack

**Comment by SeleenaJM** [comment]
Hi Jack,

It's great to hear from you that the value of both correlation coefficients can be consistently generated by the scipy and R code! 

I have uploaded sentence-level TIGEr scores on Composite and Flickr 8k to the shared folder: 
> https://drive.google.com/drive/folders/11eMgUHUD_6LLK9JmiiWCbuHjh0u2OgA1?usp=sharing,
where you could find the csv files in folder "eval_results".

Hope this can help you to figure out the problem!
Ming

**Comment by jmhessel** [comment]
Hi Ming,

Thank you so much; this is super helpful, and I really appreciate you posting these! This has helped me eliminate a variable in my analysis: I am able to re-compute the TIGEr correlations using my code, which suggests this discrepancy isn't due to the correlation computation, e.g., for composite, I get

```
Kendall tau-c TIGEr: 45.402, spearman 55.317
```

as reported in your paper! I'm still digging through some weird stuff with BLEU, SPICE, etc. scores: my code seems to differ from just about every other paper out there, including the original SPICE paper, so I know I must have something else wrong 😅. The same code that computes the TIGEr correlations computes much higher values for other metrics, e.g.,

```
Kendall tau-c TIGEr: 45.402, spearman 55.317
Kendall tau-c bleu-1: 47.100, spearman 58.054
Kendall tau-c bleu-4: 48.095, spearman 58.982
Kendall tau-c spice: 52.938, spearman 63.891
```

Were there any other preprocessing/evaluation differences you can think of? I tried with lowercasing and not, I've double checked a few examples by hand to make sure my spice scores match between the original SPICE repo, I've checked my BLEU scores against both NLTK and sacrebleu, I've tried rounding to different decimal places in case that mattered, I've tried adding a bit of random noise to break ties randomly to see if that mattered, etc.

No worries if there's nothing else you can think of, I can keep looking on my own. Thanks again for your help!!

**Comment by jmhessel** [comment]
In case you're interested (and for future readers) thanks to you: I was able to replicate the Flickr8K results! I noticed I was aggregating scores by averaging human ratings across captions, and computing correlations across 5664 unique (image, caption) pairs. But: I noticed your flickr8k file had 16992 lines --- so I tried /not/ aggregating, and, coupled with tau-c, reproduced the flickr8k results, which match both the original spice paper and TIGEr :-)

I am still working on composite (it's likely there's another dataset-specific assumption that I'm not doing as prior work did...), but I'm closer, thanks to you! :-)

**Comment by SeleenaJM** [comment]
Hi Jack,

Sorry for my late reply! It's great to hear from you that you found the problem and fixed it!  Given you got the same results on Flickr 8k, I think your implementations for existing metrics (e.g., BLEU) are correct!  For Composite, I'm wondering if you combined captions from three sources together to calculate the correlation coefficients. If not, please do that! For other potential factors, right now, I don't know yet. If I get any ideas later, I'll let you know. Hope you could get the same results on composite soon!

**Comment by jmhessel** [comment]
Quick additional update: I was able to get very similar numbers on composite, too, by removing the reference that was rated by humans from the comparison set for computing metrics, and then equalizing all captions to have 4 (instead of 5) references. That seems like a fair evaluation setup --- is this a standard setup, I wonder?

Anywho --- thanks again for all your help! :-)
